uploads = []
generated = []

[[outputs]]
id = "PbQ0yO40m2KT5JUWyoVW2"
uri = "file://checklist-translator.md"
type = "text"
title = "Checklist Implementasi: Smart Translator Training"

[[outputs]]
id = "ZAlwE3g0neZ96i8w2Zkrl"
uri = "file://blueprint-smart-translator.md"
type = "text"
title = "Blueprint & Fitur Detail - Smart Translator B (Multi-output)"

[[outputs]]
id = "1LLbJHkAXyhusZtOyPXQp"
uri = "file://checklist-smart-translator.md"
type = "text"
title = "Implementation Checklist - Smart Translator Training"
